---
- name: "Enable ufw"
  ufw: state=enabled policy=deny
  tags: firewall

- name: "Allow OpenSSH"
  ufw: rule=allow name=OpenSSH
  tags: firewall

- name: "Allow nginx"
  ufw: rule=allow name="Nginx Full"
  tags: firewall
